CREATE TABLE IF NOT EXISTS random (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  randomId VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS historic (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL
);